In [1]:
import pandas as pd
import numpy as np

In [2]:
#read .csv file
df = pd.read_csv('car_fuel_efficiency_2026.csv')

## Q1. Pandas version

In [4]:
pd.__version__

'3.0.6'

## Q2. Records count

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  str    
 2   fuel_type            10000 non-null  str    
 3   drivetrain           10000 non-null  str    
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB


## Q3. Fuel types

In [14]:
fuel_types = list(df['fuel_type'].unique())

In [16]:
type(fuel_types)

list

In [17]:
number_of_fuel_types = len(fuel_types)

In [18]:
print(number_of_fuel_types)

3


## Q4. Missing values

In [23]:
empty_cols = df.columns[df.isnull().any()].tolist()
print("Columns with empty values:", empty_cols)
print("Number of columns with empty values:", len(empty_cols))

Columns with empty values: ['horsepower', 'acceleration']
Number of columns with empty values: 2


## Q5. Max fuel efficiency

In [24]:
#Subset to get Asian cars
df_asia = df[df['origin'] == 'Asia']

#get the maximum fuel effiency
max(df_asia['fuel_efficiency_mpg'])

41.2

## Q6. Median value of horsepower

In [25]:
#Median Horsepower with missing values
intial_median = df['horsepower'].median()
print(intial_median)

254.0


In [28]:
#Get the most frequent value
mode_value = df['horsepower'].mode()
print(mode_value)

0    252.0
Name: horsepower, dtype: float64


In [34]:
#Fill missing values
last_median = df['horsepower'].fillna(mode_value).median()
print(last_median)

254.0


## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [71]:
# Select all the cars from Asia
df_asia = df[df['origin'] == "Asia"]

#Select only columns vehicle_weight and model_year
df_asia = df_asia[['vehicle_weight', 'model_year']]

#Select the first 7 values
df_asia = df_asia[:7]

# Get the underlying NumPy array. Let's call it X
X = df_asia.values
print("X:\n", X)

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX
XTX = np.dot(X.T, X)
print("\nXTX:\n", XTX)

# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
print("\nXTX_inv:\n", XTX_inv)

# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print("\ny:\n", y)

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv @ X.T @ y
print("\nw:\n", w)

# What's the sum of all the elements of the result?

total  = w.sum()
print(f"{total}")

X:
 [[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

XTX:
 [[131950500  60750580]
 [ 60750580  28041424]]

XTX_inv:
 [[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

y:
 [1100 1300  800  900 1000 1100 1200]

w:
 [0.13644777 0.2327492 ]
0.36919696904925486
